### ISSUE TITLE
Converted to coffescript and new functionalities

### ISSUE THREAD

**Issue by atika** [ashikahmad/horizontal-calendar-widget#1]
Hi! 
I converted the widget to coffescript and added some functionalities (localization (French/English), easy positioning, and customization).
I did'nt create a pull request because I also modified the Readme file…

**commit :** https://github.com/atika/Ubersicht-Horizontal-Calendar/commit/d09e81c39923224aaf1118357876082ac08d2958

https://github.com/atika/Ubersicht-Horizontal-Calendar

**Comment by ashikahmad** [comment]
Looks good :smile:! Feeling :innocent: someone found something usefull out of my code.

Actually I've created this in coffescript first and then converted to js version for the sake of curiosity :stuck_out_tongue: . By the way, this is not an `issue` and may not be here (unless you are planning to have a pull request.) So this may better be closed.

...Thanks for noticing me!
