### ISSUE TITLE
Appearance questions

### ISSUE THREAD

**Issue by cgoodwin96** [ashikahmad/horizontal-calendar-widget#3]
I'm just going to start by saying that I know nothing about coding. That being said, how can I move this widget to the bottom of my desktop and remove the grayish background? Is that even possible? Thanks in advance.

**Comment by HansWurst90** [comment]
@cgoodwin96
[Line 23 & 24](https://github.com/ashikahmad/horizontal-calendar-widget/blob/master/hcal.widget/index.js#L23) define the position of the widget.

And the value in [Line 32](https://github.com/ashikahmad/horizontal-calendar-widget/blob/master/hcal.widget/index.js#L32) is the background color. If you delete that line, the widget has no background.
