### ISSUE TITLE
Highlight Sat/Sun not Fri/Sat

### ISSUE THREAD

**Issue by skdcbrown** [ashikahmad/horizontal-calendar-widget#4]
Is there any way to highlight Saturday and Sunday instead of Friday and Saturday?

**Comment by ashikahmad** [comment]
In `/hcal.widget/index.js` file, change _line 6_:

``` js
offdayIndices: [5, 6], // Fr, Sa
```

with

``` js
offdayIndices: [0, 6], // Su, Sa
```

Note that this is just indexes mapped from _line 4_: 0=Su, 1=Mo and so on.

``` js
dayNames: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
```

**Comment by skdcbrown** [comment]
That helped a lot thank you very much!
