### ISSUE TITLE
Widget isn't working after ubersicht update

### ISSUE THREAD

**Issue by sickamongthepure** [ashikahmad/horizontal-calendar-widget#6]
I updated ubersicht to version 1.2 (47) and after that widget stopped working. It only shows "undefined" word instead of widget. I don't know how to fix it. Debug console doesn't show any errors.

**Comment by ashikahmad** [comment]
I've updated the code. Please, update the **hcal.widget** folder from latest commit and let me know if it solves for you too.

**Comment by sickamongthepure** [comment]
Yep, it solved this issue. Thanks

**Comment by ChiefPoints** [comment]
Thanks for putting this fix up so quickly, my screen was looking a bit naked ;) - all works fine now.
